runtime: python27
api_version: 1
threadsafe: true
instance_class: F1
automatic_scaling:
  min_idle_instances: 1

handlers:
- url: /static
  static_dir: static
  secure: always
- url: /.*
  script: main.app
  secure: always

libraries:
- name: ssl
  version: latest
